// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>


@interface SCNValdiCoreJSRuntimeNativeObjectsManager : NSObject

- (nonnull NSObject *)getReachableObjectsDescription;

@end
