// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/Value.hpp"

namespace snap::valdi_core {

class JSRuntimeNativeObjectsManager {
public:
    virtual ~JSRuntimeNativeObjectsManager() = default;

    virtual Valdi::Value getReachableObjectsDescription() = 0;
};

} // namespace snap::valdi_core
